Repository ros2/rmw, pull requests merged in 2018-06, with the labels that each got.

#139 proposed changes to expose_cdr pr's to use size_t
  rmw/include/rmw/serialized_message.h
  rmw/include/rmw/types.h
  rmw/src/serialized_message.c
Labels: in progress

#125 *_raw function
  rmw/CMakeLists.txt
  rmw/include/rmw/rmw.h
  rmw/include/rmw/serialized_message.h
  rmw/include/rmw/types.h
  rmw/src/serialized_message.c
  rmw/test/CMakeLists.txt
  rmw/test/test_serialized_message.cpp
Labels: in progress

#138 check the return value of rcutils_snprintf
  rmw/include/rmw/impl/cpp/macros.hpp
  rmw/src/validate_namespace.c
Labels: enhancement, in review

#140 use rcutils allocator in allocators.c to avoid direct use of malloc/free
  rmw/src/allocators.c
Labels: enhancement, in review

#141 Prepare release 0.5.0
  rmw/package.xml
  rmw_implementation_cmake/package.xml
Labels: in review
