Repository ros2/rmw, pull requests merged in 2018-11, with the labels that each got.

#153 use new error handling API
  rmw/CMakeLists.txt
  rmw/include/rmw/error_handling.h
  rmw/src/error_handling.c
  rmw/src/names_and_types.c
Labels: enhancement, in review

#161 use uint8_t instead of char for serialized message
  rmw/include/rmw/serialized_message.h
  rmw/test/test_serialized_message.cpp
Labels: in progress

#155 Methods to retrieve matched counts on publisher and subscriber
  rmw/include/rmw/rmw.h
Labels: in review

#154 refactor init to allow options to be passed and to not be global
  rmw/CMakeLists.txt
  rmw/include/rmw/init.h
  rmw/include/rmw/init_options.h
  rmw/include/rmw/ret_types.h
  rmw/include/rmw/rmw.h
  rmw/include/rmw/types.h
  rmw/src/init.c
  rmw/src/init_options.c
Labels: enhancement, in review
