Repository ros2/rmw, pull requests merged in 2019-10, with the labels that each got.

#187 add pub/sub option structures to support rmw specific payload feature
  rmw/CMakeLists.txt
  rmw/include/rmw/publisher_options.h
  rmw/include/rmw/rmw.h
  rmw/include/rmw/subscription_options.h
  rmw/include/rmw/types.h
  rmw/src/publisher_options.c
  rmw/src/subscription_options.c
Labels: enhancement

#191 add call to bump dev version to the upcoming version 0.8.1
  rmw/CMakeLists.txt
  rmw/package.xml
Labels: enhancement, in review

#185 Zero copy api
  rmw/CMakeLists.txt
  rmw/include/rmw/loaned_message_sequence.h
  rmw/include/rmw/rmw.h
  rmw/include/rmw/types.h
  rmw/src/loaned_message_sequence.c
Labels: enhancement

#190 Add function to enable localhost communication only from env var
  rmw/include/rmw/rmw.h
Labels: in review
